.TH "CFDclient" 3 "Thu May 16 2019" "CFDriver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFDclient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitSocket\fP ()"
.br
.RI "Initialize the connection to the server\&. "
.ti -1c
.RI "void \fBSocketSend\fP (string sendStr)"
.br
.RI "send commande "
.ti -1c
.RI "int \fBsend_data\fP (float[] data, string name)"
.br
.RI "Send float data\&. "
.ti -1c
.RI "int \fBsend_data\fP (int[] data, string name)"
.br
.RI "Send integer data\&. "
.ti -1c
.RI "void \fBSocketQuit\fP ()"
.br
.RI "Disconnect\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CFDriver from the source code\&.
